feat: add path label
hertz-contrib/monitor-prometheus pull request #4
Opened 2022-09-23 00:12 UTC by rogerogers

#### What type of PR is this?

feat: add path label

#### What this PR does / why we need it (English/Chinese):

en: add path label
zh: 增加路径标签

#### Which issue(s) this PR fixes:

2022-11-08 06:30 UTC, li-jin-gou requested changes

2022-11-08 06:30 UTC, li-jin-gou commented on go.mod
> +	github.com/stretchr/testify v1.8.0
add licenses

2022-11-08 06:30 UTC, li-jin-gou commented on go.sum
> +github.com/kr/text v0.1.0 h1:45sCR5RtlFHMR4UwH9sdQ5TC8v0qDQCHnXt+kaKSTVE=
use `go mod tidy && go mod verify`

2022-11-08 09:17 UTC, rogerogers commented on go.sum
> +github.com/kr/text v0.1.0 h1:45sCR5RtlFHMR4UwH9sdQ5TC8v0qDQCHnXt+kaKSTVE=
我顺便更新到最新版本了。

2022-11-08 09:18 UTC, rogerogers commented on go.mod
> +	github.com/stretchr/testify v1.8.0
done

2022-11-09 01:53 UTC, Duslia approved these changes

2022-11-09 01:54 UTC, li-jin-gou approved these changes

2022-11-09 01:54 UTC, merged